# Generated by Django 5.2.8 on 2025-12-22 02:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='User profile picture', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
