# Generated by Django 5.2.9 on 2025-12-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional_role',
            field=models.CharField(blank=True, help_text='e.g., Senior Software Engineer, Project Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Certifications, degrees, or other professional qualifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, help_text='Key skills, comma-separated (e.g., Python, Project Management, Agile)', max_length=255),
        ),
    ]
