# Generated by Django 5.2.9 on 2025-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Toggles for platform modules: dashboard, channels, projects, organization, members, analytics'),
        ),
    ]
