# Generated by Django 5.2.9 on 2025-12-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0005_remove_message_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this breakout room active?'),
        ),
        migrations.AddField(
            model_name='channel',
            name='parent_channel',
            field=models.ForeignKey(blank=True, help_text='Parent channel for breakout rooms', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='chat_channels.channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('OFFICIAL', 'Official Announcement'), ('DEPARTMENT', 'Department Channel'), ('TEAM', 'Team Channel'), ('PROJECT', 'Project Channel'), ('PRIVATE', 'Private Group'), ('DIRECT', 'Direct Message'), ('BREAKOUT', 'Breakout Room')], default='TEAM', help_text='Type of channel', max_length=20),
        ),
    ]
