# Generated by Django 5.2.9 on 2025-12-21 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0006_channel_is_active_channel_parent_channel_and_more'),
        ('organizations', '0003_sharedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='shared_project',
            field=models.ForeignKey(blank=True, help_text='Shared project this channel belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='organizations.sharedproject'),
        ),
    ]
