# Generated by Django 5.2.9 on 2025-12-25 20:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0010_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='voice_message',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Voice message audio file', max_length=255, null=True, verbose_name='voice_message'),
        ),
    ]
