# Generated by Django 5.2.9 on 2025-12-27 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0011_alter_message_voice_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, help_text='Original message if this was forwarded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='chat_channels.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Is this message pinned?'),
        ),
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, help_text='Users who starred this message', related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
