# Generated by Django 5.2.9 on 2025-12-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0013_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('EMOJI', 'Emoji'), ('VOICE', 'Voice Note'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('SYSTEM', 'System Notice')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='SENT', max_length=10),
        ),
    ]
