# Generated by Django 5.2.9 on 2026-01-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0014_message_message_type_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('EMOJI', 'Emoji'), ('VOICE', 'Voice Note'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('SYSTEM', 'System Notice')], db_index=True, default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='SENT', max_length=10),
        ),
    ]
