# Generated by Django 5.2.9 on 2026-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0017_add_message_edit_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='formatted_content',
            field=models.TextField(blank=True, help_text='HTML-formatted content from markdown', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='has_formatting',
            field=models.BooleanField(default=False, help_text='Whether message contains markdown formatting'),
        ),
    ]
