# Generated by Django 5.2.9 - SAFE VERSION WITH TABLE CHECK

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models, connection


def safely_create_tables(apps, schema_editor):
    """Check if tables exist before trying to create them"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = 'forms'
            );
        """)
        if cursor.fetchone()[0]:
            # Tables already exist - skip rest of migration
            raise migrations.Migration.AlreadyApplied("Forms tables already exist")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0019_alter_projectfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('form_type', models.CharField(choices=[('SURVEY', 'Survey'), ('FEEDBACK', 'Feedback Form'), ('REGISTRATION', 'Event Registration'), ('REQUEST', 'Service Request'), ('ASSESSMENT', 'Assessment')], default='SURVEY', max_length=20)),
                ('share_link', models.CharField(db_index=True, help_text='Unique short URL for sharing', max_length=100, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow external access without login')),
                ('allow_anonymous', models.BooleanField(default=False, help_text='Allow anonymous responses')),
                ('require_login', models.BooleanField(default=True, help_text='Require user login to submit')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('accepts_responses', models.BooleanField(default=True)),
                ('max_responses', models.IntegerField(blank=True, help_text='Maximum number of responses (blank = unlimited)', null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Auto-close form at this date/time', null=True)),
                ('send_email_on_submit', models.BooleanField(default=False)),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'db_table': 'forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=300)),
                ('field_type', models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text (Paragraph)'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('CHECKBOXES', 'Checkboxes'), ('DROPDOWN', 'Dropdown'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('TIME', 'Time'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('FILE', 'File Upload'), ('RATING', 'Rating (Stars)'), ('SCALE', 'Linear Scale'), ('SECTION', 'Section Header')], default='SHORT_TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options: ["Option 1", "Option 2"]')),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, help_text='Regex pattern for validation', max_length=200)),
                ('show_if_value', models.CharField(blank=True, help_text='Value that triggers display', max_length=200)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tools_forms.form')),
                ('show_if_field', models.ForeignKey(blank=True, help_text='Show this field only if another field has specific value', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='tools_forms.formfield')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'db_table': 'form_fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('respondent_email', models.EmailField(blank=True, help_text='Email for external/anonymous respondents', max_length=254)),
                ('answers', models.JSONField(default=dict, help_text='Field answers: {field_id: value}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tools_forms.form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
                'db_table': 'form_responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['organization', 'is_active'], name='forms_organiz_ad3816_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['created_by', '-created_at'], name='forms_created_c664e8_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form', 'order'], name='form_fields_form_id_256194_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['form', '-submitted_at'], name='form_respon_form_id_827744_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['user', '-submitted_at'], name='form_respon_user_id_f8a254_idx'),
        ),
    ]
