# Generated by Django 5.2.9 on 2025-12-21 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_department_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('access_code', models.CharField(blank=True, help_text='Code for other organizations to join', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_organizations', models.ManyToManyField(blank=True, help_text='Organizations invited to collaborate', related_name='guest_projects', to='organizations.organization')),
                ('host_organization', models.ForeignKey(help_text='Organization that owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_projects', to='organizations.organization')),
                ('members', models.ManyToManyField(blank=True, help_text='Selected members from all organizations involved', related_name='shared_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Project',
                'verbose_name_plural': 'Shared Projects',
                'db_table': 'shared_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
