# Generated by Django 5.2.9 on 2025-12-26 04:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Shared file', max_length=255, verbose_name='file'),
        ),
    ]
