# Generated by Django 5.2.9 on 2025-12-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(help_text='Shared file', upload_to='projects/files'),
        ),
    ]
