# Generated by Django 5.2.9 on 2025-12-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='headquarters',
            field=models.CharField(blank=True, help_text='HQ Location (City, Country)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Finance & Banking'), ('HEALTH', 'Healthcare'), ('EDU', 'Education'), ('MANU', 'Manufacturing'), ('RETAIL', 'Retail & E-commerce'), ('CONSULT', 'Consulting'), ('OTHER', 'Other')], default='OTHER', help_text='Primary industry', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, help_text='Company size (e.g., 10-50 employees)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Official website URL', null=True),
        ),
    ]
