# Generated by Django 5.2.9 on 2025-12-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_organization_paystack_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
    ]
