# Generated by Django 5.2.9 on 2025-12-29 14:51

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_remove_organization_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_type', models.CharField(choices=[('PROJ', 'Project'), ('DOC', 'Document'), ('FIN', 'Financial'), ('COMP', 'Compliance')], max_length=4)),
                ('audit_date', models.DateTimeField()),
                ('findings', models.JSONField(default=list, help_text='Structured findings and observations')),
                ('recommendations', models.TextField()),
                ('risk_rating', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_conducted', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='organizations.sharedproject')),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'db_table': 'audit_trails',
            },
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulation', models.CharField(choices=[('SOX', 'Sarbanes-Oxley'), ('GDPR', 'GDPR'), ('HIPAA', 'HIPAA'), ('PCI', 'PCI-DSS'), ('ISO27001', 'ISO 27001')], max_length=20)),
                ('requirement_id', models.CharField(max_length=50)),
                ('requirement_text', models.TextField()),
                ('applicable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_compliance_reqs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requirements', to='organizations.sharedproject')),
            ],
            options={
                'verbose_name': 'Compliance Requirement',
                'verbose_name_plural': 'Compliance Requirements',
                'db_table': 'compliance_requirements',
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(max_length=50)),
                ('document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('validity_period', models.DateField(help_text='When this evidence expires')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending', max_length=20)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='organizations.compliancerequirement')),
            ],
            options={
                'verbose_name': 'Compliance Evidence',
                'verbose_name_plural': 'Compliance Evidences',
                'db_table': 'compliance_evidence',
            },
        ),
        migrations.CreateModel(
            name='ControlTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_objective', models.TextField()),
                ('test_procedure', models.TextField()),
                ('sample_size', models.IntegerField()),
                ('exceptions_found', models.IntegerField(default=0)),
                ('test_result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PARTIAL', 'Partially Effective')], max_length=20)),
                ('evidence_reference', models.URLField(blank=True, help_text='Link to evidence document or location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tests', to='organizations.sharedproject')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_tested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Test',
                'verbose_name_plural': 'Control Tests',
                'db_table': 'control_tests',
            },
        ),
        migrations.CreateModel(
            name='ProjectRiskRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FIN', 'Financial'), ('SCH', 'Schedule'), ('TEC', 'Technical'), ('OPE', 'Operational'), ('COM', 'Compliance')], max_length=3)),
                ('description', models.TextField()),
                ('probability', models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], help_text='Probability of occurrence')),
                ('impact', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('mitigation_plan', models.TextField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='organizations.sharedproject')),
            ],
            options={
                'verbose_name': 'Project Risk',
                'verbose_name_plural': 'Project Risks',
                'db_table': 'project_risks',
            },
        ),
    ]
