# Generated by Django 5.2.9 on 2025-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_audittrail_compliancerequirement_complianceevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_advanced_roles',
            field=models.BooleanField(default=False, help_text='Ability to assign Auditor and Compliance Officer roles'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_governance_suite',
            field=models.BooleanField(default=False, help_text='Access to Risk & Compliance Dashboard'),
        ),
    ]
