# Generated by Django 5.2.9 on 2025-12-30 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_subscriptionplan_has_advanced_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('reference', models.CharField(help_text='Payment provider reference/ID', max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], default='paystack', max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organizations.organization')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Transaction',
                'verbose_name_plural': 'Subscription Transactions',
                'db_table': 'subscription_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
